### ISSUE TITLE
Enhance prompt.

### ISSUE THREAD

**Issue by sarg** [dustinlacewell/linkmarks#2]
Hi, there. Could you please add colon and space at the end of prompt, as `completing-read` doc suggests. This way when you enter text it doesn't stick to prompt.
```
PROMPT is a string to prompt with; normally it ends in a colon and a space.
```
https://github.com/dustinlacewell/linkmarks/blob/481a833d2eaeff54569b3c779818342bdc6a1f78/linkmarks.el#L71

**Comment by steefdebruijn** [comment]
This issue is fixed by my merge request. It is just merged into the master branch by the maintainer.
